### ISSUE TITLE
Access Website Stack improvement ideas

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#25]
To be broken down into issues and milestones...

- [x] Push metrics from w3act_export to Prometheus.
- [x] Resolve https://github.com/webrecorder/pywb/issues/591 (this is currently worked-around by dropping revisits)
- [x] Resolve https://github.com/ukwa/ukwa-pywb/issues/61 (Fixing Twitter requires indexing POST requests etc.)
- [x] ~~Find any and all places where webrender-puppeteer is used with a proxy and ensure there is no trailing slash because this make puppeteer go crazy.~~ https://github.com/ukwa/webrender-puppeteer/issues/13
- [x] Consider hooking Flask app into [Sentry](https://flask.palletsprojects.com/en/1.1.x/errorhandling/#application-errors)
- [x] Make recently-crawled screenshots (and content!) available. To do so, we have to finish off the `warc-server` idea:
    - Update warc-server to maintain filename-HDFS mapping? 
    - Then proxy across crawler warc-server and HDFS warc-server?
    - Or have a separate redirect service that bounces HDFS filenames to WebHDFS, and to the crawler warc-server otherwise?
    - Also, update warc-server to update shared file list in background thread. Could be separate services, using [NGINX proxy_next_upstream](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) to manage them.

See also https://github.com/ukwa/ukwa-access-api/issues/1 and the other issues https://github.com/ukwa/ukwa-access-api/issues
